sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jtams322/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true jtams322/docker-react npm run test
